### ISSUE TITLE
Submission problem 

### ISSUE THREAD

**Issue by birolkuyumcu** [hseelawi/JUST-Mowjaz-Competition#1]
https://competitions.codalab.org/competitions/29220

When I try to subbmision on the contest page, it gives an error

 "Invalid file type ()."

**Comment by hseelawi** [comment]
What is the type of the file you're submitting? Is it zipped?

**Comment by birolkuyumcu** [comment]
no tsv  like

"df.to_csv("../Data/outputs/answer.tsv", header=False, index=False)"

zipped ok

**Comment by birolkuyumcu** [comment]
score not calculated yet

**Comment by hseelawi** [comment]
You need to zip your file. Only the file itself, and not a folder containing it. It might require some time to evaluate after the submission.

**Comment by birolkuyumcu** [comment]
submission file name must be 'answer.tsv' and zipped 
othervise submission failed
and 
`df.to_csv("../Data/outputs/answer.tsv", header=False, index=False) `
for your ipython 
code produces a csv and this also failed
correct it  as
`df.to_csv("../Data/outputs/answer.tsv", header=False, index=False, sep='\t') `

**Comment by hseelawi** [comment]
That is true. It is an oversight from our side. We will fix it now. Thanks for pointing that out.
