### ISSUE TITLE
With regards to the Second Track.

### ISSUE THREAD

**Issue by iR00i** [hseelawi/JUST-Mowjaz-Competition#3]
Good afternoon, Ramadan Mubarak!

I would like to know if the second track “Efficiency track” is bound to the same deadline as the first track, or are we allowed to first submit results with the system description (on may/3rd) ?

Also I would like to ask whether Monday (April 19th) is included in the evaluation period where we are still allowed to submit test-set predictions or is the deadline at Sunday (April 11th) midnight ?

**Comment by hseelawi** [comment]
Sorry for the late reply. The efficiency track is open only for the top four participants in terms of performance on the leaderboard. Full details will be emailed to those participants soon.
